//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineCourse.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Course_Enrolled
    {
        public Nullable<int> User_id { get; set; }
        public Nullable<int> Course_Id { get; set; }
        public Nullable<System.DateTime> Course_Enrolleddate { get; set; }
        public Nullable<System.DateTime> Course_StartDtae { get; set; }
        public Nullable<System.DateTime> Course_CompletionDate { get; set; }
        public string Status { get; set; }
        public int Enroll_id { get; set; }
    
        public virtual Course_table Course_table { get; set; }
        public virtual User_Table User_Table { get; set; }
    }
}
